# Generated by Django 5.2.6 on 2025-09-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0001_initial'),
    ]

    operations = [
    ]
